version: '2'

services:
  webserver:
    build: ./webserver
    image: runwaytest_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../www/html:/var/www/html
    links:
      - mysql
    links:
      - "mysql:kentorii.local"
    extra_hosts:
      - "kentorii.local:${HOST_APP_IP}"

  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file: .env
